repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-case-conflict
  - id: trailing-whitespace
- repo: https://github.com/editorconfig-checker/editorconfig-checker
  rev: v3.6.1
  hooks:
  - id: editorconfig-checker
    alias: ec
- repo: local
  hooks:
  - id: shellcheck
    name: shellcheck
    entry: shellcheck
    language: system
    types: [shell]
  - id: shfmt
    name: shfmt
    entry: ./scripts/check-shfmt.sh
    language: system
    types: [shell]
