repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
    files: \.bash
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.23
  hooks:
  - id: shellcheck
- repo: local
  hooks:
  - id: check-sh
    name: check bash scripts' formats
    entry: ./scripts/shfmt-diff.bash
    language: script
